<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>..\build_tests\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>..\build_tests\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SAM_Systems\SAM.Analytical.Systems.Mollier\SAM.Analytical.Systems.Mollier.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="SAM.Analytical">
      <HintPath>..\..\SAM\build\SAM.Analytical.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core">
      <HintPath>..\..\SAM\build\SAM.Core.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Geometry">
      <HintPath>..\..\SAM\build\SAM.Geometry.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Math">
      <HintPath>..\..\SAM\build\SAM.Math.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Weather">
      <HintPath>..\..\SAM\build\SAM.Weather.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Core.Mollier">
      <HintPath>..\..\SAM_Mollier\build\SAM.Core.Mollier.dll</HintPath>
    </Reference>
    <Reference Include="SAM.Analytical.Mollier">
      <HintPath>..\..\SAM_Mollier\build\SAM.Analytical.Mollier.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\files\resources\Analytical\Systems\SystemEnergyCentre\MVRE.json" Link="files\resources\Analytical\Systems\SystemEnergyCentre\MVRE.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\files\resources\Analytical\Systems\SystemEnergyCentre\Plantroom-Only.json" Link="files\resources\Analytical\Systems\SystemEnergyCentre\Plantroom-Only.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\files\resources\Analytical\Systems\SAM_DisplaySystemManager.JSON" Link="resources\Analytical\Systems\SAM_DisplaySystemManager.JSON" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
